name: push_to_docker_hub
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login for Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKER_CLI: docker

      - name: Build and Push Image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag samuelmata/mataresesamuel-lb324:latest .
          docker push samuelmata/mataresesamuel-lb324:latest
        env:
          DOCKER_CLI: docker
          DOCKER_BUILDKIT: 1
