name: push_to_docker_hub
on:
  push:
    branches:
      - main
  repository_dispatch:
    types:
      - secret_changed:
        secrets:
          - APPLICATION_PASSWORD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login for Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag samuelmata/mataresesamuel-lb324:latest --build-arg PASSWORD="${{ secrets.APPLICATION_PASSWORD }}" . --push
        env:
          DOCKER_CLI: docker
          DOCKER_BUILDKIT: 1
