name: push_to_docker_hub
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: secret_changed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create .env file
        run: |
          echo "PASSWORD=${{ secrets.APPLICATION_PASSWORD }}" > $GITHUB_WORKSPACE/.env
        env:
          PASSWORD: ${{ secrets.APPLICATION_PASSWORD }}

      - name: Display .env file
        run: cat $GITHUB_WORKSPACE/.env

      - name: Login for Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Image
        run: |
          docker buildx create --use
          docker buildx build --file Dockerfile --tag samuelmata/mataresesamuel-lb324:latest . --push
        env:
          DOCKER_CLI: docker
          DOCKER_BUILDKIT: 1
